lang: it

project:
  type: website
  output-dir: docs

website:
  title: "home"
  navbar:
    right:
      - href: https://psicostat.dpss.psy.unipd.it/
        text: "<img src='/images/faviconpsicostat2.png' style='height: 22px; margin-top: -4px;'>"
      - icon: github
        href: https://github.com/EnricoToffalini

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



