lang: it

project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    left: 
      - href: https://enricotoffalini.github.io
        text: "enricotoffalini.github.io"
        target: _blank
    right:
      - href: https://psicostat.dpss.psy.unipd.it/
        text: "<img src='/images/faviconpsicostat2.png' style='height: 22px; margin-top: -4px;'>"
      - icon: github
        href: https://github.com/EnricoToffalini

format:
  html:
    include-in-header:
       text: |
          <link rel="shortcut icon" href="favicon.ico"/> 
          <script data-goatcounter="https://toffeeblog.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
    theme:
      - cosmo
      - brand
    css: styles.css



